name: build

on:
  push:
    tags:
    - v*

concurrency:
  group: build-${{ github.head_ref }}

jobs:
  build:
    name: Build wheels and source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build
      run: python -m build

    - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@29930c9cf57955dc1b98162d0d8bc3ec80d9e75c # v1.8.4
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
